# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MyProjects\GUI_project\SetConfig.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetConfig(object):
    def setupUi(self, SetConfig):
        SetConfig.setObjectName("SetConfig")
        SetConfig.resize(714, 565)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        SetConfig.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/resources/linux_216px_1210908_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SetConfig.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SetConfig)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(121, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_wo = QtWidgets.QLabel(self.centralwidget)
        self.lb_wo.setObjectName("lb_wo")
        self.verticalLayout.addWidget(self.lb_wo)
        spacerItem3 = QtWidgets.QSpacerItem(82, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lb_aproval_no = QtWidgets.QLabel(self.centralwidget)
        self.lb_aproval_no.setObjectName("lb_aproval_no")
        self.verticalLayout.addWidget(self.lb_aproval_no)
        spacerItem4 = QtWidgets.QSpacerItem(82, 32, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.lb_prod_qty = QtWidgets.QLabel(self.centralwidget)
        self.lb_prod_qty.setObjectName("lb_prod_qty")
        self.verticalLayout.addWidget(self.lb_prod_qty)
        spacerItem5 = QtWidgets.QSpacerItem(82, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.lb_guy_send = QtWidgets.QLabel(self.centralwidget)
        self.lb_guy_send.setObjectName("lb_guy_send")
        self.verticalLayout.addWidget(self.lb_guy_send)
        spacerItem6 = QtWidgets.QSpacerItem(182, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.lb_guy_receive = QtWidgets.QLabel(self.centralwidget)
        self.lb_guy_receive.setObjectName("lb_guy_receive")
        self.verticalLayout.addWidget(self.lb_guy_receive)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_version_sw = QtWidgets.QLineEdit(self.centralwidget)
        self.le_version_sw.setObjectName("le_version_sw")
        self.verticalLayout_2.addWidget(self.le_version_sw)
        spacerItem8 = QtWidgets.QSpacerItem(182, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.cb_chipcode = QtWidgets.QComboBox(self.centralwidget)
        self.cb_chipcode.setObjectName("cb_chipcode")
        self.cb_chipcode.addItem("")
        self.cb_chipcode.addItem("")
        self.verticalLayout_2.addWidget(self.cb_chipcode)
        spacerItem9 = QtWidgets.QSpacerItem(182, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.cb_vendor_code = QtWidgets.QComboBox(self.centralwidget)
        self.cb_vendor_code.setObjectName("cb_vendor_code")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.cb_vendor_code.addItem("")
        self.verticalLayout_2.addWidget(self.cb_vendor_code)
        spacerItem10 = QtWidgets.QSpacerItem(182, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.le_date_sw = QtWidgets.QLineEdit(self.centralwidget)
        self.le_date_sw.setPlaceholderText("")
        self.le_date_sw.setObjectName("le_date_sw")
        self.verticalLayout_2.addWidget(self.le_date_sw)
        spacerItem11 = QtWidgets.QSpacerItem(182, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.cb_ext_version = QtWidgets.QComboBox(self.centralwidget)
        self.cb_ext_version.setObjectName("cb_ext_version")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.cb_ext_version.addItem("")
        self.verticalLayout_2.addWidget(self.cb_ext_version)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.bt_save = QtWidgets.QPushButton(self.centralwidget)
        self.bt_save.setObjectName("bt_save")
        self.gridLayout.addWidget(self.bt_save, 4, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 3, 1, 1, 1)
        SetConfig.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SetConfig)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 26))
        self.menubar.setObjectName("menubar")
        SetConfig.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SetConfig)
        self.statusbar.setObjectName("statusbar")
        SetConfig.setStatusBar(self.statusbar)

        self.retranslateUi(SetConfig)
        QtCore.QMetaObject.connectSlotsByName(SetConfig)

    def retranslateUi(self, SetConfig):
        _translate = QtCore.QCoreApplication.translate
        SetConfig.setWindowTitle(_translate("SetConfig", "二级比对参数设置"))
        self.lb_wo.setText(_translate("SetConfig", "软件版本："))
        self.lb_aproval_no.setText(_translate("SetConfig", "芯片代码："))
        self.lb_prod_qty.setText(_translate("SetConfig", "厂商代码："))
        self.lb_guy_send.setText(_translate("SetConfig", "版本日期："))
        self.lb_guy_receive.setText(_translate("SetConfig", "外部版本："))
        self.le_version_sw.setText(_translate("SetConfig", "V02S03LGWT0100"))
        self.cb_chipcode.setItemText(0, _translate("SetConfig", "03"))
        self.cb_chipcode.setItemText(1, _translate("SetConfig", "01"))
        self.cb_vendor_code.setItemText(0, _translate("SetConfig", "65"))
        self.cb_vendor_code.setItemText(1, _translate("SetConfig", "BD"))
        self.cb_vendor_code.setItemText(2, _translate("SetConfig", "BG"))
        self.cb_vendor_code.setItemText(3, _translate("SetConfig", "BW"))
        self.cb_vendor_code.setItemText(4, _translate("SetConfig", "CL"))
        self.cb_vendor_code.setItemText(5, _translate("SetConfig", "CY"))
        self.cb_vendor_code.setItemText(6, _translate("SetConfig", "DW"))
        self.cb_vendor_code.setItemText(7, _translate("SetConfig", "ES"))
        self.cb_vendor_code.setItemText(8, _translate("SetConfig", "FC"))
        self.cb_vendor_code.setItemText(9, _translate("SetConfig", "GD"))
        self.cb_vendor_code.setItemText(10, _translate("SetConfig", "GY"))
        self.cb_vendor_code.setItemText(11, _translate("SetConfig", "HB"))
        self.cb_vendor_code.setItemText(12, _translate("SetConfig", "HL"))
        self.cb_vendor_code.setItemText(13, _translate("SetConfig", "HR"))
        self.cb_vendor_code.setItemText(14, _translate("SetConfig", "HT"))
        self.cb_vendor_code.setItemText(15, _translate("SetConfig", "HY"))
        self.cb_vendor_code.setItemText(16, _translate("SetConfig", "JC"))
        self.cb_vendor_code.setItemText(17, _translate("SetConfig", "JF"))
        self.cb_vendor_code.setItemText(18, _translate("SetConfig", "JH"))
        self.cb_vendor_code.setItemText(19, _translate("SetConfig", "JN"))
        self.cb_vendor_code.setItemText(20, _translate("SetConfig", "JR"))
        self.cb_vendor_code.setItemText(21, _translate("SetConfig", "KD"))
        self.cb_vendor_code.setItemText(22, _translate("SetConfig", "LD"))
        self.cb_vendor_code.setItemText(23, _translate("SetConfig", "LN"))
        self.cb_vendor_code.setItemText(24, _translate("SetConfig", "NK"))
        self.cb_vendor_code.setItemText(25, _translate("SetConfig", "NL"))
        self.cb_vendor_code.setItemText(26, _translate("SetConfig", "NZ"))
        self.cb_vendor_code.setItemText(27, _translate("SetConfig", "PH"))
        self.cb_vendor_code.setItemText(28, _translate("SetConfig", "RS"))
        self.cb_vendor_code.setItemText(29, _translate("SetConfig", "SD"))
        self.cb_vendor_code.setItemText(30, _translate("SetConfig", "SS"))
        self.cb_vendor_code.setItemText(31, _translate("SetConfig", "SX"))
        self.cb_vendor_code.setItemText(32, _translate("SetConfig", "TC"))
        self.cb_vendor_code.setItemText(33, _translate("SetConfig", "TX"))
        self.cb_vendor_code.setItemText(34, _translate("SetConfig", "WE"))
        self.cb_vendor_code.setItemText(35, _translate("SetConfig", "WN"))
        self.cb_vendor_code.setItemText(36, _translate("SetConfig", "WS"))
        self.cb_vendor_code.setItemText(37, _translate("SetConfig", "XJ"))
        self.cb_vendor_code.setItemText(38, _translate("SetConfig", "XL"))
        self.cb_vendor_code.setItemText(39, _translate("SetConfig", "YD"))
        self.cb_vendor_code.setItemText(40, _translate("SetConfig", "YH"))
        self.cb_vendor_code.setItemText(41, _translate("SetConfig", "ZN"))
        self.le_date_sw.setText(_translate("SetConfig", "190325"))
        self.cb_ext_version.setItemText(0, _translate("SetConfig", "0001"))
        self.cb_ext_version.setItemText(1, _translate("SetConfig", "0002"))
        self.cb_ext_version.setItemText(2, _translate("SetConfig", "0090"))
        self.cb_ext_version.setItemText(3, _translate("SetConfig", "0121"))
        self.cb_ext_version.setItemText(4, _translate("SetConfig", "0151"))
        self.cb_ext_version.setItemText(5, _translate("SetConfig", "0181"))
        self.cb_ext_version.setItemText(6, _translate("SetConfig", "0211"))
        self.cb_ext_version.setItemText(7, _translate("SetConfig", "0270"))
        self.cb_ext_version.setItemText(8, _translate("SetConfig", "0301"))
        self.cb_ext_version.setItemText(9, _translate("SetConfig", "0331"))
        self.cb_ext_version.setItemText(10, _translate("SetConfig", "0361"))
        self.cb_ext_version.setItemText(11, _translate("SetConfig", "0421"))
        self.cb_ext_version.setItemText(12, _translate("SetConfig", "0451"))
        self.cb_ext_version.setItemText(13, _translate("SetConfig", "0481"))
        self.cb_ext_version.setItemText(14, _translate("SetConfig", "0541"))
        self.cb_ext_version.setItemText(15, _translate("SetConfig", "0570"))
        self.cb_ext_version.setItemText(16, _translate("SetConfig", "0600"))
        self.cb_ext_version.setItemText(17, _translate("SetConfig", "0630"))
        self.cb_ext_version.setItemText(18, _translate("SetConfig", "1090"))
        self.cb_ext_version.setItemText(19, _translate("SetConfig", "2090"))
        self.cb_ext_version.setItemText(20, _translate("SetConfig", "2181"))
        self.cb_ext_version.setItemText(21, _translate("SetConfig", "2541"))
        self.cb_ext_version.setItemText(22, _translate("SetConfig", "0212"))
        self.cb_ext_version.setItemText(23, _translate("SetConfig", "0101"))
        self.cb_ext_version.setItemText(24, _translate("SetConfig", "0151"))
        self.cb_ext_version.setItemText(25, _translate("SetConfig", "0482"))
        self.cb_ext_version.setItemText(26, _translate("SetConfig", "0302"))
        self.cb_ext_version.setItemText(27, _translate("SetConfig", "0452"))
        self.cb_ext_version.setItemText(28, _translate("SetConfig", "0122"))
        self.cb_ext_version.setItemText(29, _translate("SetConfig", "0182"))
        self.cb_ext_version.setItemText(30, _translate("SetConfig", "1091"))
        self.cb_ext_version.setItemText(31, _translate("SetConfig", "0091"))
        self.cb_ext_version.setItemText(32, _translate("SetConfig", "2091"))
        self.cb_ext_version.setItemText(33, _translate("SetConfig", "0631"))
        self.cb_ext_version.setItemText(34, _translate("SetConfig", "0661"))
        self.cb_ext_version.setItemText(35, _translate("SetConfig", "0062"))
        self.bt_save.setText(_translate("SetConfig", "保存配置"))
import apprcc_rc
