# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Python\GUI_project\STA_config.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_STA_config(object):
    def setupUi(self, STA_config):
        STA_config.setObjectName("STA_config")
        STA_config.resize(1022, 395)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        STA_config.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/resources/windows_704px_1210167_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        STA_config.setWindowIcon(icon)
        STA_config.setWindowOpacity(1.0)
        STA_config.setToolTip("")
        STA_config.setToolTipDuration(-1)
        self.gridLayout = QtWidgets.QGridLayout(STA_config)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb1 = QtWidgets.QLabel(STA_config)
        self.lb1.setObjectName("lb1")
        self.verticalLayout.addWidget(self.lb1)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lb2 = QtWidgets.QLabel(STA_config)
        self.lb2.setObjectName("lb2")
        self.verticalLayout.addWidget(self.lb2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.lb3 = QtWidgets.QLabel(STA_config)
        self.lb3.setObjectName("lb3")
        self.verticalLayout.addWidget(self.lb3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lb4 = QtWidgets.QLabel(STA_config)
        self.lb4.setObjectName("lb4")
        self.verticalLayout.addWidget(self.lb4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lb5 = QtWidgets.QLabel(STA_config)
        self.lb5.setObjectName("lb5")
        self.verticalLayout.addWidget(self.lb5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.lb6 = QtWidgets.QLabel(STA_config)
        self.lb6.setObjectName("lb6")
        self.verticalLayout.addWidget(self.lb6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb7 = QtWidgets.QLabel(STA_config)
        self.lb7.setObjectName("lb7")
        self.verticalLayout_2.addWidget(self.lb7)
        spacerItem6 = QtWidgets.QSpacerItem(17, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.lb8 = QtWidgets.QLabel(STA_config)
        self.lb8.setObjectName("lb8")
        self.verticalLayout_2.addWidget(self.lb8)
        spacerItem7 = QtWidgets.QSpacerItem(17, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.lb9 = QtWidgets.QLabel(STA_config)
        self.lb9.setObjectName("lb9")
        self.verticalLayout_2.addWidget(self.lb9)
        spacerItem8 = QtWidgets.QSpacerItem(17, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.lb10 = QtWidgets.QLabel(STA_config)
        self.lb10.setObjectName("lb10")
        self.verticalLayout_2.addWidget(self.lb10)
        spacerItem9 = QtWidgets.QSpacerItem(17, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.lb11 = QtWidgets.QLabel(STA_config)
        self.lb11.setObjectName("lb11")
        self.verticalLayout_2.addWidget(self.lb11)
        spacerItem10 = QtWidgets.QSpacerItem(17, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.lb12 = QtWidgets.QLabel(STA_config)
        self.lb12.setObjectName("lb12")
        self.verticalLayout_2.addWidget(self.lb12)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt1 = QtWidgets.QPushButton(STA_config)
        self.bt1.setObjectName("bt1")
        self.verticalLayout_4.addWidget(self.bt1)
        spacerItem12 = QtWidgets.QSpacerItem(14, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.bt2 = QtWidgets.QPushButton(STA_config)
        self.bt2.setObjectName("bt2")
        self.verticalLayout_4.addWidget(self.bt2)
        spacerItem13 = QtWidgets.QSpacerItem(14, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.bt3 = QtWidgets.QPushButton(STA_config)
        self.bt3.setObjectName("bt3")
        self.verticalLayout_4.addWidget(self.bt3)
        spacerItem14 = QtWidgets.QSpacerItem(14, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.bt4 = QtWidgets.QPushButton(STA_config)
        self.bt4.setObjectName("bt4")
        self.verticalLayout_4.addWidget(self.bt4)
        spacerItem15 = QtWidgets.QSpacerItem(14, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem15)
        self.bt5 = QtWidgets.QPushButton(STA_config)
        self.bt5.setObjectName("bt5")
        self.verticalLayout_4.addWidget(self.bt5)
        spacerItem16 = QtWidgets.QSpacerItem(14, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.bt6 = QtWidgets.QPushButton(STA_config)
        self.bt6.setObjectName("bt6")
        self.verticalLayout_4.addWidget(self.bt6)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem17 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cb1 = QtWidgets.QCheckBox(STA_config)
        self.cb1.setObjectName("cb1")
        self.verticalLayout_3.addWidget(self.cb1)
        spacerItem18 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.cb2 = QtWidgets.QCheckBox(STA_config)
        self.cb2.setObjectName("cb2")
        self.verticalLayout_3.addWidget(self.cb2)
        spacerItem19 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.cb3 = QtWidgets.QCheckBox(STA_config)
        self.cb3.setObjectName("cb3")
        self.verticalLayout_3.addWidget(self.cb3)
        spacerItem20 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        self.cb4 = QtWidgets.QCheckBox(STA_config)
        self.cb4.setObjectName("cb4")
        self.verticalLayout_3.addWidget(self.cb4)
        spacerItem21 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem21)
        self.cb5 = QtWidgets.QCheckBox(STA_config)
        self.cb5.setObjectName("cb5")
        self.verticalLayout_3.addWidget(self.cb5)
        spacerItem22 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem22)
        self.cb6 = QtWidgets.QCheckBox(STA_config)
        self.cb6.setObjectName("cb6")
        self.verticalLayout_3.addWidget(self.cb6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem23 = QtWidgets.QSpacerItem(13, 371, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem23)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lb13 = QtWidgets.QTextBrowser(STA_config)
        self.lb13.setObjectName("lb13")
        self.verticalLayout_5.addWidget(self.lb13)
        spacerItem24 = QtWidgets.QSpacerItem(13, 22, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem24)
        self.bt7 = QtWidgets.QPushButton(STA_config)
        self.bt7.setObjectName("bt7")
        self.verticalLayout_5.addWidget(self.bt7)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(STA_config)
        QtCore.QMetaObject.connectSlotsByName(STA_config)

    def retranslateUi(self, STA_config):
        _translate = QtCore.QCoreApplication.translate
        STA_config.setWindowTitle(_translate("STA_config", "STA成品工装参数配置"))
        self.lb1.setText(_translate("STA_config", "厂商代码："))
        self.lb2.setText(_translate("STA_config", "芯片代码："))
        self.lb3.setText(_translate("STA_config", "版本日期："))
        self.lb4.setText(_translate("STA_config", "版本号："))
        self.lb5.setText(_translate("STA_config", "硬件版本ID："))
        self.lb6.setText(_translate("STA_config", "详细版本信息："))
        self.lb7.setText(_translate("STA_config", "GD"))
        self.lb8.setText(_translate("STA_config", "03"))
        self.lb9.setText(_translate("STA_config", "2019年3月25日"))
        self.lb10.setText(_translate("STA_config", "00 01"))
        self.lb11.setText(_translate("STA_config", "135"))
        self.lb12.setText(_translate("STA_config", "V02S03LGWT0100"))
        self.bt1.setText(_translate("STA_config", "修改厂商代码"))
        self.bt2.setText(_translate("STA_config", "修改芯片ID"))
        self.bt3.setText(_translate("STA_config", "修改版本日期"))
        self.bt4.setText(_translate("STA_config", "修改版本号"))
        self.bt5.setText(_translate("STA_config", "修改硬件版本ID"))
        self.bt6.setText(_translate("STA_config", "修改详细版本信息"))
        self.cb1.setText(_translate("STA_config", "过零检测"))
        self.cb2.setText(_translate("STA_config", "三相过零检测"))
        self.cb3.setText(_translate("STA_config", "一级厂商代码"))
        self.cb4.setText(_translate("STA_config", "二级厂商代码"))
        self.cb5.setText(_translate("STA_config", "芯片ID检测"))
        self.cb6.setText(_translate("STA_config", "模块ID写入"))
        self.lb13.setHtml(_translate("STA_config", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:24pt; color:#ff6666;\">请注意，</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\'; font-size:24pt; color:#ff6666;\">配置文件尚未保存！</span></p></body></html>"))
        self.bt7.setText(_translate("STA_config", "保存配置文件"))
import apprcc_rc
